server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  elasticsearch:
    rest:
      uris: http://192.168.8.10:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.8.10
    virtual-host: /gmall
    username: admin
    password: admin
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
        concurrency: 3

feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug