server:
  port: 18010
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart?useSSL=true
    username: root
    password: 123456
  redis:
    host: localhost
feign:
  sentinel:
    enabled: true
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
auth:
  jwt:
    pubKeyPath: /Users/zhouguopeng/Documents/IdeaWorkSpace/gmall/gmall-0420/gmall-cart/key/rsa/rsa.pub
    cookieName: GMALL-TOKEN
    userKey: user-key
    expire: 15552000